server:
  port: 8089

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    service-url:
      defaultZone: http://www.scdemo.com:8080/eureka/
    healthcheck:
      enabled: true

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo-test?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9092
          min-partition-count: 1
          auto-create-topics: true
          auto-add-partitions: true
      bindings:
        input:
          destination: order-user
          group: g1
          consumer:
            autoCommitOffset: false
            concurrency: 1
            partitioned: false
      default:
        producer:
          headerMode: embeddedHeaders

