server:
  port: 8085

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    service-url:
      defaultZone: http://www.scdemo.com:8080/eureka/
    healthcheck:
      enabled: true


spring:
  application:
    name: zuul-service
  zipkin:
    base-url: http://www.scdemo.com:9411
  sleuth:
    sampler:
      percentage: 1.0

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: ribbon-service
    api-b:
      path: /api-b/**
      serviceId: fegin-service


