server:
  port: 8080
eureka:
  instance:
    hostname: www.scdemo.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://www.scdemo.com:8080/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000
spring:
  application:
    name: eureka-server
