spring:
  application:
    name: config-server
  cloud:
    config:
      server:
       git:
         uri: https://github.com/xdongs2009/spring-clound-demo/
         search-paths: config
         username:
         password:
      label: master
server:
  port: 8086


