spring:
  application:
    name: config-server
  cloud:
    config:
      server:
       git:
         uri: https://github.com/xdongs2009/spring-clound-demo/
         search-paths: config
         username:
         password:
      label: master

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    service-url:
      defaultZone: http://www.scdemo.com:8080/eureka/
    healthcheck:
      enabled: true

server:
  port: 8086


